### ISSUE TITLE
spark-publish: retry `.addMeasurements`

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-api#293]
The publishing iteration often fails for intermittent RPC-API-related reasons that could be worked around by retrying the step committing the measurements batch CID.

- We incorrectly estimated the gas needed by the transaction and set the gas limit too low.
- Glif RPC API failed with 504 Gateway Time-out.
- (possibly more)

This does not affect the performance & correctness of the entire system (the next iteration will retry everything). However, it wastes resources.

- The DB query listing 100k measurements can take a long time to complete if we are under load and there are too many measurements waiting to be published.
- The data we upload to web3.storage becomes orphaned.

Let's implement a retry logic for the entire step "commit to the smart contract", i.e. a top-level retry for both `.addMeasurements` + `tx.wait()`.

Slack discussion: https://space-meridian.slack.com/archives/C06RPCL6QGL/p1715590945617159

**Comment by bajtos** [comment]
Excerpts from the Slack discussion.

---

spark-publish is repeatedly encountering “transaction execution reverted” errors. When I load the TX in Filfox, I see it has the status `SysErrOutOfGas`. I think that means we set the gas limit too low. If that’s the case, then I propose to slightly increase the gas limit calculated by ethers, e.g. to 120% or 150%.
https://filfox.info/en/message/0x383ef49a73a8dd637eb25cf4b49b70d6e575f779533404f9d8e8d3115fb7237c?t=1

![Screenshot 2024-05-13 at 11 03 51](https://github.com/filecoin-station/spark-api/assets/1140553/d8b756aa-5dec-4193-9a7e-51bbc300a527)

A few minutes later, the next TX was processed successfully.
https://filfox.info/en/message/0xae196933c814e88ee71d56398e880b2b634ee664580a9f9c177970ec92d2159e?t=4
```
Gas Limit:  37,536,545
Gas Used:   30,034,436
```

---

I found another example where we could not call .addMeasurements, and it would make sense to retry. Notice also that the iteration took 638s (>10min).

```
2024-05-14T08:52:11Z app[6e82994bee5798] cdg [info]Invoking ie.addMeasurements()...
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]Error: server response 504 Gateway Time-out (request={  }, response={  }, error=null, code=SERVER_ERROR, version=6.10.0)
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]    at makeError (file:///app/node_modules/ethers/lib.esm/utils/errors.js:124:21)
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]    at assert (file:///app/node_modules/ethers/lib.esm/utils/errors.js:143:15)
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]    at FetchResponse.assertOk (file:///app/node_modules/ethers/lib.esm/utils/fetch.js:822:9)
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]    at JsonRpcProvider._send (file:///app/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:880:18)
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]    at async file:///app/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:277:40 {
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]  code: 'SERVER_ERROR',
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]  request: FetchRequest {},
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]  response: FetchResponse {},
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]  error: undefined,
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]  shortMessage: 'server response 504 Gateway Time-out'
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]}
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]Bad exit code: 1
2024-05-14T09:02:16Z app[6e82994bee5798] cdg [info]Done. This iteration took 638303ms.
```

**Comment by bajtos** [comment]
The problem is still there.

```
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]Error: transaction execution reverted (action="sendTransaction", data=null, reason=null, invocation=null, revert=null, transaction={ "data": "", "from": "0x53bDfdEa92f7A60aeF82228926d02878018acB4e", "to": "0x8460766Edc62B525fc1FA4D628FC79229dC73031" }, receipt={ "_type": "TransactionReceipt", "blobGasPrice": null, "blobGasUsed": null, "blockHash": "0xb8f9b5153431e9fe9226f0a6283bac53b97c03fa9f4c1cd21366039cbfffb582", "blockNumber": 3918884, "contractAddress": null, "cumulativeGasUsed": "0", "from": "0x53bDfdEa92f7A60aeF82228926d02878018acB4e", "gasPrice": "597053", "gasUsed": "8540225", "hash": "0xe87ae4c47409a22218c4c954ba0fc223a42da576ea79d4749c7c18cb40c3aa45", "index": 69, "logs": [  ], "logsBloom": "0x00f310000021480400010cd8a804b0a2012d00100580234004000028c0303a13a0c0490cc40005019b084a0b1400d4830821040102013b646218004024249128806b041001052208701a72b8419848220248020082041200080702208003501a80004c44520010a403a804a30080ca950080000418880423007105910088c5810802a0000f5500011a00a202060110009000520100c0e08a940413404882483103040c2500880204aa802452004404421000008400000710821e01a1066848812048041216418e0102242001c534808232b2928a80011010054d240041306898801915009882203c00c00084c205403020100000610000561261062c8708d000", "root": "0x0000000000000000000000000000000000000000000000000000000000000000", "status": 0, "to": "0x8460766Edc62B525fc1FA4D628FC79229dC73031" }, code=CALL_EXCEPTION, version=6.12.1)
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    at makeError (file:///app/node_modules/ethers/lib.esm/utils/errors.js:124:21)
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    at assert (file:///app/node_modules/ethers/lib.esm/utils/errors.js:143:15)
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    at checkReceipt (file:///app/node_modules/ethers/lib.esm/providers/provider.js:1119:13)
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    at JsonRpcProvider.txListener (file:///app/node_modules/ethers/lib.esm/providers/provider.js:1165:33)
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  code: 'CALL_EXCEPTION',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  action: 'sendTransaction',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  data: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  reason: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  invocation: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  revert: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  transaction: {
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    to: '0x8460766Edc62B525fc1FA4D628FC79229dC73031',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    from: '0x53bDfdEa92f7A60aeF82228926d02878018acB4e',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    data: ''
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  },
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  receipt: TransactionReceipt {
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    provider: JsonRpcProvider {},
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    to: '0x8460766Edc62B525fc1FA4D628FC79229dC73031',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    from: '0x53bDfdEa92f7A60aeF82228926d02878018acB4e',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    contractAddress: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    hash: '0xe87ae4c47409a22218c4c954ba0fc223a42da576ea79d4749c7c18cb40c3aa45',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    index: 69,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    blockHash: '0xb8f9b5153431e9fe9226f0a6283bac53b97c03fa9f4c1cd21366039cbfffb582',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    blockNumber: 3918884,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    logsBloom: '0x00f310000021480400010cd8a804b0a2012d00100580234004000028c0303a13a0c0490cc40005019b084a0b1400d4830821040102013b646218004024249128806b041001052208701a72b8419848220248020082041200080702208003501a80004c44520010a403a804a30080ca950080000418880423007105910088c5810802a0000f5500011a00a202060110009000520100c0e08a940413404882483103040c2500880204aa802452004404421000008400000710821e01a1066848812048041216418e0102242001c534808232b2928a80011010054d240041306898801915009882203c00c00084c205403020100000610000561261062c8708d000',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    gasUsed: 8540225n,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    blobGasUsed: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    cumulativeGasUsed: 0n,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    gasPrice: 597053n,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    blobGasPrice: null,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    type: 2,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    status: 0,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]    root: '0x0000000000000000000000000000000000000000000000000000000000000000'
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  },
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  shortMessage: 'transaction execution reverted',
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  attemptNumber: 1,
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]  retriesLeft: 5
2024-05-16T15:22:33Z app[6e82994bee5798] cdg [info]}
```
